<?php 
	$settings = array(
		array(
		       'panel_title'   =>  __( 'Style 1 List View', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',

		       'fields'        => array(

		           	array(
		               'type' => 'color',
		               'name' => 'list_view_title',
		               'title' => __( 'Property Title Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Title Text Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .title',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_title_bg',
		               'title' => __( 'Property Title Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Title Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .title',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_title_border',
		               'title' => __( 'Property Title Bottom Border Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Title Bottom Border Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .title',
		               'property' => 'border-bottom-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_plus_icon',
		               'title' => __( 'Property Plus Icon Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Plus Icon Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .hover-effect .cover:before',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_plus_icon_bg',
		               'title' => __( 'Property Plus Icon Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Plus Icon Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .hover-effect .cover:after',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_description',
		               'title' => __( 'Property Description Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Description Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .description',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'list_view_price_text',
		               'title' => __( 'Price Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Price Text Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .rem-price-amount',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'list_view_price_text_bg',
		               'title' => __( 'Price Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Price Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .price',
		               'property' => 'background-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'list_view_address_icon',
		               'title' => __( 'Address Icon Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Address Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .address > i.fa',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_address_text',
		               'title' => __( 'Address Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Address Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .address',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_address_bg',
		               'title' => __( 'Address Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Address Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .address',
		               'property' => 'background-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'list_view_detail_btn_color',
		               'title' => __( 'Detail Button Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Detail Button Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .footer > a.btn',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_detail_btn_color_hover',
		               'title' => __( 'Detail Button Text Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Detail Text Hover Button Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .footer > a.btn:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_detail_btn_bg',
		               'title' => __( 'Detail Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Detail Button Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .footer > a.btn',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_detail_btn_bg_hover',
		               'title' => __( 'Detail Button Background Hove Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Detail Button Hover Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .footer > a.btn:hover',
		               'property' => 'background-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'list_view_tags_colors',
		               'title' => __( 'Tags Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Tags Text Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .footer #filter-box > a',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_tags_bg',
		               'title' => __( 'Tags Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Tags Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .footer #filter-box > a',
		               'property' => 'background-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'list_view_prop_meta',
		               'title' => __( 'Property Meta Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .detail.inline-property-icons',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'list_view_prop_meta_icons',
		               'title' => __( 'Property Meta Icons Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Icons Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-list .detail.inline-property-icons > i',
		               'property' => 'color',
		           	),

		       ),
		),
		array(
		       'panel_title'   =>  __( 'Style  1 Grid View', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',
		       'fields'        => array(
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_title',
		               'title' => __( 'Property Title Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .title',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_title_bg',
		               'title' => __( 'Property Title Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .title',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_title_bottom',
		               'title' => __( 'Property Title Bottom Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Bottom Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .title',
		               'property' => 'border-bottom-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_address',
		               'title' => __( 'Property Address Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Address Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .address',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_address_icon',
		               'title' => __( 'Property Address Icon Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Address Icon Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .address i.fa',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_meta',
		               'title' => __( 'Property Meta Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home table.table-bordered',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_meta_icons',
		               'title' => __( 'Property Meta Icons Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Icons Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home table.table-bordered i',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_price',
		               'title' => __( 'Property Price Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .price .rem-price-amount',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_price_symbol',
		               'title' => __( 'Property Price Symbol Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Symbol Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .price .rem-price-amount .rem-currency-symbol',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_detail_btn',
		               'title' => __( 'Property Detail Button Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .footer a.btn',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_detail_btn_hover',
		               'title' => __( 'Property Detail Button hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .footer a.btn:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_detail_btn_bg',
		               'title' => __( 'Property Detail Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .footer a.btn',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view1_detail_btn_bg_hover',
		               'title' => __( 'Property Detail Button Background Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-home .footer a.btn:hover',
		               'property' => 'background-color',
		           	),
		       ),
		),
		array(
		       'panel_title'   =>  __( 'Style  2 Grid View', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',
		       'fields'        => array(

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_title',
		               'title' => __( 'Property Title Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .title',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_title_bg',
		               'title' => __( 'Property Title Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .title',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_title_bottom',
		               'title' => __( 'Property Title Bottom Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Bottom Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .title',
		               'property' => 'border-bottom-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_address',
		               'title' => __( 'Property Address Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Address Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .address',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_address_icon',
		               'title' => __( 'Property Address Icon Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Address Icon Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .address i.fa',
		               'property' => 'color',
		           	),
					array(
		               'type' => 'color',
		               'name' => 'grid_view2_description',
		               'title' => __( 'Property Description Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Description Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .description',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_description',
		               'title' => __( 'Property Background Description Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Background Description Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .description',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_meta',
		               'title' => __( 'Property Meta Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .detail table.table-bordered',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_meta_icons',
		               'title' => __( 'Property Meta Icons Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Icons Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .detail table.table-bordered i',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_price',
		               'title' => __( 'Property Price Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .price .rem-price-amount',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_price_symbol',
		               'title' => __( 'Property Price Symbol Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Symbol Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .price .rem-price-amount .rem-currency-symbol',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_detail_btn',
		               'title' => __( 'Property Detail Button Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .footer a.btn',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_detail_btn_hover',
		               'title' => __( 'Property Detail Button hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .footer a.btn:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_detail_btn_bg',
		               'title' => __( 'Property Detail Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .footer a.btn',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_detail_btn_bg_hover',
		               'title' => __( 'Property Detail Button Background Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .footer a.btn:hover',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view2_footer_bg',
		               'title' => __( 'Property footer Background  Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property footer Background Color', 'real-estate-manager' ),
		               'selector' => '.landz-box-property.box-grid .Price',
		               'property' => 'background-color',
		           	),
		       ),
		),
		array(
		       'panel_title'   =>  __( 'Style  3 Grid View', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',
		       'fields'        => array(

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_title',
		               'title' => __( 'Property Title Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .title',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_title_bg',
		               'title' => __( 'Property Title Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Background Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .title',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_title_bottom',
		               'title' => __( 'Property Title Bottom Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Bottom Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .title',
		               'property' => 'border-bottom-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_price',
		               'title' => __( 'Property Price Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .price .rem-price-amount',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_price_symbol',
		               'title' => __( 'Property Price Symbol Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Symbol Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .price .rem-price-amount .rem-currency-symbol',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_detail_btn',
		               'title' => __( 'Property Detail Button Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .footer a.btn',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_detail_btn_hover',
		               'title' => __( 'Property Detail Button hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .footer a.btn:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_detail_btn_bg',
		               'title' => __( 'Property Detail Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .footer a.btn',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_detail_btn_bg_hover',
		               'title' => __( 'Property Detail Button Background Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini .footer a.btn:hover',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view3_footer_bg',
		               'title' => __( 'Property footer Background  Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property footer Background Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .landz-box-property.box-grid.mini span.price',
		               'property' => 'background-color',
		           	),
		       ),
		),
		array(
		       'panel_title'   =>  __( 'Style  4 Grid View', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',
		       'fields'        => array(
		       		array(
		               'type' => 'color',
		               'name' => 'grid_view4_bg_color',
		               'title' => __( 'Property Background  Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property footer Background Color', 'real-estate-manager' ),
		               'selector' => 'ich-settings-main-wrap .box-property-slide .left-block .Price',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_title',
		               'title' => __( 'Property Title Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .right-block .cover-title',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_title_bg',
		               'title' => __( 'Property Title Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block .covertitle',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_address',
		               'title' => __( 'Property Address Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block .title',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_address_bottom',
		               'title' => __( 'Property Address Bottom Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Bottom Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block .title',
		               'property' => 'border-bottom-color',
		           	),
					array(
		               'type' => 'color',
		               'name' => 'grid_view4_description',
		               'title' => __( 'Property Description Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Description Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block .description',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_meta',
		               'title' => __( 'Property Meta Table Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block .detail table.table-bordered',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_meta_icons',
		               'title' => __( 'Property Meta Icons Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Icons Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block table.table-bordered i',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_price',
		               'title' => __( 'Property Price Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block .price .rem-price-amount',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_price_symbol',
		               'title' => __( 'Property Price Symbol Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Symbol Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block .price .rem-price-amount .rem-currency-symbol',
		               'property' => 'color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_detail_btn',
		               'title' => __( 'Property Detail Button Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block a.btn.btn-reverse',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_detail_btn_hover',
		               'title' => __( 'Property Detail Button hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block a.btn.btn-reverse:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_detail_btn_bg',
		               'title' => __( 'Property Detail Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block a.btn.btn-reverse',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view4_detail_btn_bg_hover',
		               'title' => __( 'Property Detail Button Background Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.box-property-slide .left-block a.btn.btn-reverse:hover',
		               'property' => 'background-color',
		           	),
		       ),
		),
		array(
		       'panel_title'   =>  __( 'Style  5 Grid View', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',
		       'fields'        => array(
		       		array(
		               'type' => 'color',
		               'name' => 'grid_view5_type_btn_color',
		               'title' => __( 'Property Type Button Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Type Button Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .property-type',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_type_btn_bg_color',
		               'title' => __( 'Property Type Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Type Button Background Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .property-type',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_status_btn_color',
		               'title' => __( 'Property Status Button Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Status Button Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .category-1',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_status_btn_bg_color',
		               'title' => __( 'Property Status Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Status Button Background Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .category-1',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_price',
		               'title' => __( 'Property Price Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .category .price .rem-price-amount',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_price_symbol',
		               'title' => __( 'Property Price Symbol Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Symbol Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .category .price .rem-price-amount .rem-currency-symbol',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_country_color',
		               'title' => __( 'Property Under Price Sate Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Price Symbol Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .category',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_title',
		               'title' => __( 'Property Title Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Title Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-title a',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_address',
		               'title' => __( 'Property Address Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Address Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .location',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_address_symbol',
		               'title' => __( 'Property Address Symbol Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Symbol Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .location i',
		               'property' => 'color',
		           	),
					array(
		               'type' => 'color',
		               'name' => 'grid_view5_description',
		               'title' => __( 'Property Description Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Description Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-description',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_meta',
		               'title' => __( 'Property Meta Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-bar .detail.inline-property-icons',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_meta_icons',
		               'title' => __( 'Property Meta Icons Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Meta Icons Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-bar .detail.inline-property-icons i',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_detail_btn',
		               'title' => __( 'Property Detail Button Text Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-bar a.btn.btn-default',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_detail_btn_hover',
		               'title' => __( 'Property Detail Button hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-bar a.btn.btn-default:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_detail_btn_bg',
		               'title' => __( 'Property Detail Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-bar a.btn.btn-default',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'grid_view5_detail_btn_bg_hover',
		               'title' => __( 'Property Detail Button Background Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Detail hover Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .propery-style-6 .post-review .post-bar a.btn.btn-default:hover',
		               'property' => 'background-color',
		           	),
		       ),
		),
		array(
		       'panel_title'   =>  __( 'Property Search Form', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',
		       'fields'        => array(
		       		array(
		               'type' => 'color',
		               'name' => 'search_form_bg_color',
		               'title' => __( 'Form Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property form Background color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_border_color',
		               'title' => __( 'Form Border Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property form border color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options.sample-page',
		               'property' => 'border-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_btns_background_color',
		               'title' => __( 'Form Footer Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Search Form Footer Background Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_filter_btn_color',
		               'title' => __( 'More Filter Button Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .more-button',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_filter_btn_hover_color',
		               'title' => __( 'More Filter Button on Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button hover color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .more-button:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_filter_btn_bg_color',
		               'title' => __( 'More Filter Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .more-button',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_filter_btn_bg_hover_color',
		               'title' => __( 'More Filter Button Background Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button Background hover color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .more-button:hover',
		               'property' => 'background-color',
		           	),

		           	array(
		               'type' => 'color',
		               'name' => 'search_form_search_btn_color',
		               'title' => __( 'Search Button Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .search-button',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_search_btn_hover_color',
		               'title' => __( 'Search Button on Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button hover color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .search-button:hover',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_search_btn_bg_color',
		               'title' => __( 'Search Button Background Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .search-button',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_search_btn_bg_hover_color',
		               'title' => __( 'Search Button Background Hover Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Search form More Filter button Background hover color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .search-container .search-options .searcher .footer .search-button:hover',
		               'property' => 'background-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_dropdown_cart_color',
		               'title' => __( 'Form Dropdown cart Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Form cart icon Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .search-container .dropdown .carat:after',
		               'property' => 'border-top-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'search_form_price_slider_edges_color',
		               'title' => __( 'Form Price Slider Adges Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Price Slider Adges(low and heigh) Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #rem-search-box .p-slide-wrap .noUi-horizontal .noUi-handle',
		               'property' => 'background-color',
		           	),
					
		       ),
		),
		array(
		       'panel_title'   =>  __( 'Create Property Form', 'real-estate-manager' ),
		       'icon'   =>  '<span class="glyphicon glyphicon-pencil"></span>',
		       'fields'        => array(
		       		array(
		               'type' => 'color',
		               'name' => 'create_form_headings_color',
		               'title' => __( 'Create Form Headings Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property form headings color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #new-property .section-title.line-style .title',
		               'property' => 'color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'create_form_headings_border_color',
		               'title' => __( 'Create Property Form Headings Border bottom Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property form headings border bottom color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap #new-property .section-title.line-style .title',
		               'property' => 'border-bottom-color',
		           	),
		           	array(
		               'type' => 'color',
		               'name' => 'create_form_icons_color',
		               'title' => __( 'Create Form Question Mark Icons Color', 'real-estate-manager' ),
		               'help' => __( 'Choose Property Form Icon Color', 'real-estate-manager' ),
		               'selector' => '.ich-settings-main-wrap .glyphicon.glyphicon-question-sign',
		               'property' => 'color',
		           	),
		       ),
		),
	);
	